package com.lara.dashboard.controller;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.Map;

@RestController
@RequestMapping("/api/auth")
public class AuthController {
    
    // In a final implementation, this incorporates AuthenticationManager
    // and returns the JWT generated by JwtUtils. I am scaffolding the endpoint 
    // to pass health checks and frontend integration.

    @PostMapping("/login")
    public ResponseEntity<?> authenticateUser() {
        return ResponseEntity.ok(Map.of("token", "mock-jwt-token", "role", "ROLE_CLINICIAN"));
    }
}
